# This workflow will build a package using Maven and then publish it to GitHub packages when a PR is accepted/new content is pushed
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Publish Snapshot

on:
  workflow_dispatch:
  push:
    branches: 
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: admin
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Setup Postgres
      run: psql -f ci/sql/setup_postgres.sql postgresql://postgres:admin@localhost:5432/postgres

    - name: Build with Maven
      run: |
        mkdir -p ~/.m2
        echo "<settings><servers><server><id>Eclipse BaSyx SDK GitHub Packages</id><username>x-access-token</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
        mvn -B package --file basyx.components/pom.xml
      env:       
        GITHUB_TOKEN: ${{ github.token }}

    - name: Delete old sdk package
      uses: actions/delete-package-versions@v1
      continue-on-error: true
      with:
        package-name: 'org.eclipse.basyx.basyx.sdk'

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy --file basyx.components/pom.xml -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
