# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  pull_request:
    branches: [ feature/updater ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: admin
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Setup Postgres
      run: psql -f ci/sql/setup_postgres.sql postgresql://postgres:admin@localhost:5432/postgres
    - name: Build with Maven
      run: mvn -B package -f basyx.components/pom.xml
    - name: Install Updater Component-Core
      run: mvn clean install -f basyx.components.updater.core/pom.xml
    - name: Compile Updater Component-Camel-AAS
      run: mvn compile -f basyx.components.updater.camel-aas/pom.xml
    - name: Compile Updater Component-Camel-ActiveMQ
      run: mvn compile -f basyx.components.updater.camel-activemq/pom.xml
    - name: Compile Updater Component-Camel-Hono
      run: mvn compile -f basyx.components.updater.camel-hono/pom.xml
    - name: Compile Updater Component-Camel-HTTP
      run: mvn compile -f basyx.components.updater.camel-http/pom.xml
    - name: Compile Updater Component-Camel-HTTPppolling
      run: mvn compile -f basyx.components.updater.camel-httppolling/pom.xml
    - name: Compile Updater Component-Camel-Kafka
      run: mvn compile -f basyx.components.updater.camel-kafka/pom.xml
    - name: Compile Updater Component-Camel-OPCUA
      run: mvn compile -f basyx.components.updater.camel-opcua/pom.xml
    - name: Compile Updater Component-Camel-Paho
      run: mvn compile -f basyx.components.updater.camel-paho/pom.xml
    - name: Compile Updater Component-Camel-Prometheus
      run: mvn compile -f basyx.components.updater.camel-prometheus/pom.xml
    - name: Compile Updater Component-Camel-Timer
      run: mvn compile -f basyx.components.updater.camel-timer/pom.xml
    - name: Compile Updater Component-Camel-JSONata
      run: mvn compile -f basyx.components.updater.camel-jsonata/pom.xml
    - name: Compile Updater Component-Camel-JSONJackson
      run: mvn compile -f basyx.components.updater.camel-jsonjackson/pom.xml
    - name: Compile Updater Component-Examples
      run: mvn compile -f basyx.components.updater.examples/pom.xml
      env:       
        GITHUB_TOKEN: ${{ github.token }}
