# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Install PostgreSQL 
      run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql
    - name: Change permissions of postgres init script
      run: chmod +x ./ci/init_postgres.sh
    - name: Configure postgres
      run: ./ci/init_postgres.sh postgres 
      env:
        PGDATA: run/postgresql/data
        POSTGRES_PASSWORD: admin
    - name: Start postgres
      run: pg_ctl start
    - name: Build with Maven
      run: mvn -B package --file basyx.components/pom.xml
